image: node:lts

stages:
  - lint
  - test
  - package
  - publish

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
  - yarn install

lint:
  stage: lint
  only:
    - branches
  script:
    - yarn lint

test:
  stage: test
  only:
    - branches
  script:
    - yarn test

mutation-test:
  stage: test
  only:
    - branches
  script:
    - yarn mutation-test

package:
  stage: package
  only:
    - branches
  script:
    - yarn build

publish:
  stage: publish
  only:
    - master
  script:
    - echo "placeholder"
