version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: node:lts

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ~/repo/node_modules

  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
      - run: yarn lint
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
      - run: yarn test
  mutation-test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
      - run: yarn mutation-test
  publish:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Compile for deployment
          command: yarn build
      - run:
          name: Authenticate to NPM
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish the package
          command: npm publish --dry-run
workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires: 
            - build
      - mutation-test:
          requires: 
            - build
      - publish:
          requires:
            - build
            - lint
            - test
            - mutation-test
          filters:
            branches:
              only: master